### ISSUE TITLE
Bug: Lyrics command doesn't work

### ISSUE THREAD

**Issue by DirectX-Luck** [eritislami/evobot#120]
![4](https://user-images.githubusercontent.com/62919102/86509987-f3beb480-bda0-11ea-9dcd-f81520b3574f.png)
Please fix it.

**Comment by eritislami** [comment]
The lyrics are scraped from google search results see here: [lyrics-finder](https://www.npmjs.com/package/lyrics-finder), if it doesn't find anything there isnt anything i can do about it. I chose to use this package because i didn't want to add another api & key to the bot. If you don't like it or disagree with my code just fork it and make your own changes.
