### ISSUE TITLE
🐛Bot won't respond to any command

### ISSUE THREAD

**Issue by zack-kyria** [eritislami/evobot#1371]
I installed the latest version.
1) cd evobot
2) npm install
3) fixed config
4) npm start run

and the bot just doesn't respond to anything.
Looks online but no command works

**Comment by ADRAMMELECH-AI** [comment]
the bot has done the conversion to the slash commands, you can find all the updates here:
https://github.com/eritislami/evobot/commit/047ec3803addcab1c3764da30990c5e0fe190fe9
the new version dosn't show any info but normally works fine, maybe you trying to use the old commad, anyways, the bot dosn't work right now because this bug: 
https://github.com/eritislami/evobot/issues/1368#issue-1607718686

**Comment by eritislami** [comment]
Pushed a new release https://github.com/eritislami/evobot/releases/tag/2.6.1
