### ISSUE TITLE
How can i call the function play on index.js

### ISSUE THREAD

**Issue by wesleyjp** [eritislami/evobot#138]
Hi.
I just want to make a little increment on bot, but i don't know much about node or discord bot programing, i just have the basic java script knowledge.
So i want to make the bot join a channel and automatic start playing a song after the member enter in the channel.
I manage to make the bot join after member join but i can't call the function play in the script.
Can you give me a tip how to call the function play.
Thank you for supporting.

index.js

```
client.on("voiceStateUpdate", (oldMember, newMember)=> {
    const channel = client.channels.cache.get("551860196230823946");
    const newUserChannel = newMember.channelID;
    const oldUserChannel = oldMember.channelID;
  
  if(newUserChannel === channel.id) {
      channel.join();
      play() <== Need Help Here 
    }
  
  })
```

**Comment by eritislami** [comment]
I can explain how to make this work but i don't have time to write the code for you, right now there is no fast easy way to do this because the play command requires a message to be sent in a discord channel, what you can do is to just copy the play command and rename it to something else and you have to delete everything that depends on the message parameter, you will also have to modify the queue code as well if you want to check if something is already playing. If you need code help you will have to ask in discord.js official discord server
