### ISSUE TITLE
Reaction Based Volume Control

### ISSUE THREAD

**Issue by lakhindar572** [eritislami/evobot#164]
It's great if we can control the volume using emoji baesd button by reacting.
For stop, pause , resume , it already have these features. Please add volume control too.

**Comment by eritislami** [comment]
Hey thanks for the suggestion, as of 93351dd73d9eef23268fa4f770ac00d992164504 I have added reactions for volume control (mute,-vol,+vol)
It increases and decreases by 10% on every reaction

**Comment by SugarD-x** [comment]
I noticed after using the volume mute and unmute, it is setting the bot's volume forcefully back to 100%, not respecting prior settings or the default amount set in the files. (I manually changed mine to a default of 30%). If you set the volume by command, it briefly goes to that percentage and then raises back to 100% by quickly fading the volume higher.

**Comment by SugarD-x** [comment]
As an update, I changed the affected code in ```/include/play.js``` to fix these issues. It's not the cleanest fix, but it works for its purpose without heavy modifications:

```        case "🔇":
          reaction.users.remove(user).catch(console.error);
          if (!canModifyQueue(member)) return;
          if (queue.volume <= 0) {
            queue.volume = volumeold;
            queue.connection.dispatcher.setVolumeLogarithmic(queue.volume / 100);
            queue.textChannel.send(`${user} 🔊 unmuted the music!`).catch(console.error);
          } else {
			global.volumeold = queue.volume;
            queue.volume = 0;
            queue.connection.dispatcher.setVolumeLogarithmic(0);
            queue.textChannel.send(`${user} 🔇 muted the music!`).catch(console.error);
          }
          break;```

I basically just set ```queue.connection.dispatcher.setVolumeLogarithmic``` to use ```queue.volume``` rather than 100, and grabbed the old ```queue.volume``` prior to muting so I could restore it during the unmuting process. This also fixes the issue with the volume forcing its way back to 100% after unmuting and manually changing the volume again. (I'm still not sure why it did that to begin with).
