### ISSUE TITLE
Media Controls via Reactions Disappear 

### ISSUE THREAD

**Issue by LR25** [eritislami/evobot#3]
When your playing a song and you go to pause it after 5 minutes the Media Controls via Reactions get removed. Meaning you have to manually type /resume or /skip. 

I've also noticed once the song has been resumed it will play for around 20 seconds and then go silent. It will resume after about 30 seconds and play the song for a few seconds and then skip to the next song. Once the next song plays on the queue it will only play for a short period of time and then the bot leaves.

👍

**Comment by eritislami** [comment]
I could leave the reactions up on the message forever but the issue is if you click a reaction from an old message by the bot it will affect the current playing music, example if you click the pause reaction on a message that was posted a few hours ago it will pause the music playing at the moment, i will try to work on a solution to remove old reactions and that should fix this issue

As for the second part of your issue, i haven't noticed this behaviour myself on my machine but i will have to do further testing, it might be due to the stream buffer but im not exactly sure about that

**Comment by eritislami** [comment]
6826e25, Changed the media control reactions to last 30 minutes after each message
