### ISSUE TITLE
add permissions 

### ISSUE THREAD

**Issue by husosh** [eritislami/evobot#358]
add perms, so people cant spam the stuff like like /stop and /play 
also im not sure how to remove the reactions from the message in play.js

**Comment by evrardco** [comment]
I'm willing to give this a try. 
I was thinking about putting a DJ_ROLE string which would be compared against in the config.json file.

But before I get my hands dirty with that, is anyone already working on this ? @eritislami

**Comment by eritislami** [comment]
I'm not working on it and I don't know if anyone else is, its up to you if you want to do it.

**Comment by dylanjamesdev** [comment]
I would like to say that this would be super useful but please keep in mind the intent limitations for verified bots while coding this.

**Comment by booleans-oss** [comment]
Is anyone working on this feature? @evrardco @eritislami @dylanjamesdev 

> I would like to say that this would be super useful but please keep in mind the intent limitations for verified bots while coding this.

Yep. Verified bots would need to have whitelisted access to the intent (`GUILD_MEMBERS`). But I think that most bots do have this intent as it is pretty convenient not to have GuildMembers information.

**Comment by titanabrian** [comment]
Is this issues assigned to someone?

**Comment by evrardco** [comment]
I'll be working on it tomorrow :)

**Comment by evrardco** [comment]
I made a pull request with a crude implementation of a role checking. I added a new setting DJ_ROLE in the config.json which can be left to undefined for the default "free for all" behavior. 
If you specify a role name that exists in the bot's guild (server) the bot can only be used by those who have that role. 
I sticked to a crude implementation because I felt it stayed to true to the lightweight and easy to use spirit of the bot :)
