### ISSUE TITLE
Bug: Error: Error parsing info: Unable to retrieve video metadata

### ISSUE THREAD

**Issue by DEV-TGX** [eritislami/evobot#406]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1.
2.
 
**Expected behavior**
A description of what you expected to happen.

**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by totolerigolo324** [comment]
I have the same problem as you. So I looked in the ytdl-core api and not ytdl-core-discord because for me the problem comes from a problem recovering data from the video. I have looked at all the code in this API and I think the problem is not with the evobot code but a problem between youtube and ytdl-core. (maybe because of recent events, GitHub had even deleted the GitHub from ytdl-core ...)

**Comment by eritislami** [comment]
There are duplicate issues for this already, please check first
