### ISSUE TITLE
Laggy music

### ISSUE THREAD

**Issue by BlueMax15** [eritislami/evobot#706]
Whenever I play a song, it's laggy even though I have a good internet connection (~200 Mbps). I tried changing the server region but it doesn't work. Help me.

**Comment by zorrigas** [comment]
Sounds like a network or cpu problem

**Comment by Moquent** [comment]
> Whenever I play a song, it's laggy even though I have a good internet connection (~200 Mbps). I tried changing the server region but it doesn't work. Help me.

@BlueMax15 what I understand from your problem is that you don't have a server which can support ffmpeg fully. It depends on your CPU architecture mainly iirc. There's nothing you can do about this iirc.

If your bot is in a huge amount of servers I recommend you change your player from YTDL to something like Lavalink (easiest) or Lavaplayer (Java).
