### ISSUE TITLE
Radio Streaming System

### ISSUE THREAD

**Issue by rexjohannes** [eritislami/evobot#722]
**Is your feature request related to a problem? Please describe.**
I want an Bot that can play Music an Radio too.
**Describe the solution you'd like**
An Radio System with an list of radios and custom url support as arg or an radio list api
**Describe alternatives you've considered**
/
**Additional context**
/

**Comment by rexjohannes** [comment]
#771

**Comment by SugarD-x** [comment]
Pull request #711 does allow for MP3 streaming, but from my personal testing, it doesn't support things like ShoutCast streams, (including ShoutCast v2). It appears to be specific to just MP3 file types with that exact extension because of the way the code is written.

If someone has a solution for internet radio stream support, (especially ShoutCast v2), I'd love to add that to my bot too. 😃

**Comment by rexjohannes** [comment]
`connection.play("linktomp3orshoutcasturl")`

**Comment by SrIzan10** [comment]
Tried with m3u streams. It doesn't work.

**Comment by wolf-yuan-6115** [comment]
@SrIzan10 do u mean m3u8?

**Comment by SrIzan10** [comment]
No, just m3u.




Saturday, 7 August 2021, 1:39 PM +0200 from Wolf yuan  ***@***.***>:
***@***.*** do u mean m3u8?

**Comment by SugarD-x** [comment]
Same issue. It only seems to handle .mp3 extensions, which is all it was written for. Most internet radio streams tend to rely on playlist extensions so the player reads the listen URL through it, and that usually doesn't have an extension. It works great with .mp3, though.

**Comment by SrIzan10** [comment]
Yeah, but normally it’s not the most common file format for radio stations.

Saturday, 7 August 2021, 1:59 PM +0200 from SugarD-x  ***@***.***>:
