### ISSUE TITLE
Bug: Multiple 'Leaving voice channel' messages

### ISSUE THREAD

**Issue by beanman109** [eritislami/evobot#950]
**Describe the bug**
If you play a youtube video through the bot and the queue ends, but you play another video before the inactivity timer from the 'STAY_TIME' variable removes the bot from the voice channel, it posts the 'Leaving voice channel' message several times depending on how many videos were played.

**How To Reproduce**
1. Play a youtube video through the bot.
2. Wait for the youtube video to end & the "Music queue ended." message
3. Play another youtube video before the bot disconnects due to inactivity.
 
**Expected behavior**
Once the bot leaves the discord channel due to inactivity it should only announce once.

**Environment (add if possible)**
Docker Image - eritislami/evobot:0.15.2 also tested eritislami/evobot:latest
* Node.js version: 

**Additional information & screenshots**

![evobot1](https://user-images.githubusercontent.com/79735138/134783530-cbdb72c5-8284-42d3-99ca-c9ba5154c664.png)
![evobot2](https://user-images.githubusercontent.com/79735138/134783532-0ae45078-918f-4658-bf22-702ebeea31ed.png)

**Comment by eritislami** [comment]
Are you sure you don't have multiple instances running with the same token?

**Comment by beanman109** [comment]
> 
> 
> Are you sure you don't have multiple instances running with the same token?

1 Instance of the bot running with 1 token, I have tested it in a separate instance with a new token & the same bug occurs.
No other messages are repeating when using other commands only the 'Leaving voice channel' message repeats if following the steps above.

![evobot3](https://user-images.githubusercontent.com/79735138/134793088-d5b97bf0-f504-4739-8a4c-da909d260a7c.png)

**Comment by sandrzejewskipl** [comment]
I had the same issue when STAY_TIME was set on docker image. Similar issue #944

**Comment by KAAquilla** [comment]
same issue today

**Comment by drewburr** [comment]
I was able to reproduce this locally. It's definitely the impact of environment variables not being converted to an integer. 

In this case, the wait time of 60 seconds gets handled fine when we [use multiplication](https://github.com/eritislami/evobot/blob/master/include/play.js#L27) to convert seconds to milliseconds, but it doesn't seem to play nice in the cooldown loop, which appears to also handle the process of disconnecting the bot after the queue has ended. The issue seems to be similar to #944, where [addition](https://github.com/eritislami/evobot/blob/master/index.js#L68) ends up converting ints to strings. I should have a PR opened soon
